#!/usr/bin/env ruby

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

num1 = 1
num2 = 2
next_num = 0

sum = 0
sum += num1 if num1 % 2 == 0
sum += num2 if num2 % 2 == 0

while next_num < 4_000_000
  next_num = num1 + num2
  num1 = num2
  num2 = next_num
  sum += next_num if next_num % 2 == 0
end

puts "Answer: #{sum}"
